AgencjaNieruchomosciXYZ_Project/force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

AgencjaNieruchomosciXYZ_Project/force-app/main/default/objects/Property__c/fields/m__c.field-meta.xml
<CustomField>
    <fullName>m__c</fullName>
    <label>m²</label>
    <precision>5</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

AgencjaNieruchomosciXYZ_Project/force-app/main/default/objects/Property__c/fields/Property_City__c.field-meta.xml
<CustomField>
    <fullName>Property_City__c</fullName>
    <label>Property City</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

AgencjaNieruchomosciXYZ_Project/force-app/main/default/objects/Property__c/fields/Property_Number__c.field-meta.xml
<CustomField>
    <fullName>Property_Number__c</fullName>
    <label>Property Number</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

AgencjaNieruchomosciXYZ_Project/force-app/main/default/objects/Property__c/fields/Property_Post_Code__c.field-meta.xml
<CustomField>
    <fullName>Property_Post_Code__c</fullName>
    <label>Property Post Code</label>
    <length>6</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

AgencjaNieruchomosciXYZ_Project/force-app/main/default/objects/Property__c/fields/Property_State__c.field-meta.xml
<CustomField>
    <fullName>Property_State__c</fullName>
    <label>Property State</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dolnośląskie</fullName>
            </value>
            <value>
                <fullName>Kujawsko-Pomorskie</fullName>
            </value>
            <value>
                <fullName>Lubelskie</fullName>
            </value>
            <value>
                <fullName>Lubuskie</fullName>
            </value>
            <value>
                <fullName>Łódzkie</fullName>
            </value>
            <value>
                <fullName>Małopolskie</fullName>
            </value>
            <value>
                <fullName>Mazowieckie</fullName>
            </value>
            <value>
                <fullName>Opolskie</fullName>
            </value>
            <value>
                <fullName>Podkarpackie</fullName>
            </value>
            <value>
                <fullName>Podlaskie</fullName>
            </value>
            <value>
                <fullName>Pomorskie</fullName>
            </value>
            <value>
                <fullName>Sląskie</fullName>
            </value>
            <value>
                <fullName>Świętokrzyskie</fullName>
            </value>
            <value>
                <fullName>Warmińsko-Mazurskie</fullName>
            </value>
            <value>
                <fullName>Wielkopolskie</fullName>
            </value>
            <value>
                <fullName>Zachodniopomorskie</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

AgencjaNieruchomosciXYZ_Project/force-app/main/default/objects/Property__c/fields/Property_Street__c.field-meta.xml
<CustomField>
    <fullName>Property_Street__c</fullName>
    <label>Property Street</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

AgencjaNieruchomosciXYZ_Project/force-app/main/default/objects/Property__c/recordTypes/House.recordType-meta.xml
<RecordType>
    <fullName>House</fullName>
    <active>true</active>
    <description>Jeśli chcesz wprowadzić nowy dom lub mieszkanie do systemu, wybierz &quot;House&quot;</description>
    <label>House</label>
</RecordType>

AgencjaNieruchomosciXYZ_Project/force-app/main/default/objects/Property__c/recordTypes/Office.recordType-meta.xml
<RecordType>
    <fullName>Office</fullName>
    <active>true</active>
    <description>Jeśli chcesz wprowadzić nowe biuro do systemu, wybierz &quot;Office&quot;</description>
    <label>Office</label>
</RecordType>

AgencjaNieruchomosciXYZ_Project/force-app/main/default/classes/TriggerPopulatePropertyNameTest.cls
@isTest
public with sharing class TriggerPopulatePropertyNameTest {
    @isTest
    static void testPopulatePropertyName() {

        Property__c testProperty = new Property__c();
        testProperty.Property_City__c = 'Test City';
        testProperty.Property_Street__c = 'Test Street';
        testProperty.Property_Number__c = '123';
        testProperty.Property_State__c = 'Dolnośląskie';
        testProperty.Property_Post_Code__c = '54-124';
        testProperty.m__c = 100;
        testProperty.Purchase_Price__c = 2137;
        testProperty.RecordTypeId = Schema.SObjectType.Property__c.getRecordTypeInfosByName().get('House').getRecordTypeId();
        insert testProperty;
        
        Property__c insertedProperty = [SELECT Name FROM Property__c WHERE Id = :testProperty.Id];
        System.assertEquals(insertedProperty.Name, 'Dom/Mieszk | Test City | Test Street 123');
        
        testProperty.RecordTypeId = Schema.SObjectType.Property__c.getRecordTypeInfosByName().get('Office').getRecordTypeId();
        update testProperty;
        
        insertedProperty = [SELECT Name FROM Property__c WHERE Id = :testProperty.Id];
        System.assertEquals(insertedProperty.Name, 'Biuro | Test City | Test Street 123');
    }
}